# Generated by Django 6.0.2 on 2026-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('qr', 'QR'), ('card', 'Card')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
