# Generated by Django 6.0.2 on 2026-04-13 11:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('user', 'video')},
        ),
    ]
