# Generated by Django 6.0.4 on 2026-04-13 17:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
