# Generated by Django 6.0.4 on 2026-04-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(max_length=255, upload_to='videos/'),
        ),
    ]
