# Generated by Django 6.0.2 on 2026-04-20 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('key_takeaways', models.TextField(blank=True, null=True)),
                ('important_terms', models.TextField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Instructor who created or reviewed the notes', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='notes.videonotes')),
            ],
            options={
                'ordering': ['notes', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserNoteProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_read', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('last_read_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.notesection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_progress', to=settings.AUTH_USER_MODEL)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='notes.videonotes')),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'notes')},
            },
        ),
        migrations.CreateModel(
            name='NoteBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='notes.notesection')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='notes.videonotes')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'notes', 'section')},
            },
        ),
    ]
